### ISSUE TITLE
Warnings when building bridge.h

### ISSUE THREAD

**Issue by branhost** [rakion99/Axon#29]
I was trying to update the Axon source and I put all the addresses in. I built the project as Debug Win32 and got a lot of warnings for the file bridge.h:
```
bridge.h(32): warning C4838: conversion from 'int' to 'const char' requires a narrowing conversion

bridge.h(32): warning C4309: 'initializing': truncation of constant value

bridge.h(227): warning C4244: 'initializing': conversion from 'lua_Number' to 'int', possible loss of data

bridge.h(236): warning C4002: too many actual parameters for macro 'r_lua_tostring'

bridge.h(276): warning C4244: 'initializing': conversion from 'double' to 'int', possible loss of data
```

Please fix the warnings in the code when you get the chance! Thanks

**Comment by rakion99** [comment]
nah i don't even use it or play roblox anymore, and since you are using this source you should already know enough c++ and reverse engineering so its easy cake to fix these warnings, if not then you shouldn't be using sources without even knowing what are you doing, if that is the case i recommend to delete this and start learning c++ if you want to continue with this type of stuff.

**Comment by branhost** [comment]
It turns out that I didn't get the right address for each lua function. Thanks for the advice too.

**Comment by branhost** [comment]
It turns out that my addresses were incorrect but thanks for the advice!
